using Microsoft.EntityFrameworkCore;

namespace MVC_AutoGeneratedCRUD.Model
{
    public class ApplicationDbContext : DbContext
    {
        public required DbSet<Client> Clients { get; set; }
        public required DbSet<Comment> Comments { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string connectionString = @"
                Data Source=NADI\SQLEXPRESS;
                Initial Catalog=clients_db_pv324;
                Integrated Security=SSPI;
                Timeout=10;
                TrustServerCertificate=true;
            ";
            optionsBuilder.UseSqlServer(connectionString);
        }
    }
}
