namespace MVC_AutoGeneratedCRUD.Model
{
    // Comment - класс, описывающий комментарий клиента
    public class Comment
    {
        public int Id { get; set; }
        public int Rating { get; set; }
        public string Text { get; set; } = string.Empty;
        public int? ClientId { get; set; }
        public Client? Client { get; set; }

        public Comment() { }
    }
}
