using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MVC_AutoGeneratedCRUD.Model;

namespace MVC_AutoGeneratedCRUD.Pages.Comments
{
    public class IndexModel : PageModel
    {
        private readonly MVC_AutoGeneratedCRUD.Model.ApplicationDbContext _context;

        public IndexModel(MVC_AutoGeneratedCRUD.Model.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Comment> Comment { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Comment = await _context.Comments
                .Include(c => c.Client).ToListAsync();
        }
    }
}
